# Generated by Django 5.2.11 on 2026-02-23 05:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('script_path', models.CharField(blank=True, help_text='Full server path to script', max_length=500)),
                ('run_command', models.CharField(blank=True, help_text='e.g. python /home/scrapers/run.py', max_length=1000)),
                ('log_folder_path', models.CharField(blank=True, help_text='Full path to log folder', max_length=500)),
                ('mongo_collection_name', models.CharField(blank=True, max_length=200)),
                ('mongo_db_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_scrapers', to='dashboard.mainscraper')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_string', models.CharField(default='0 6,14,22 * * *', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_scraper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='dashboard.subscraper')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_inserted', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sub_scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_history', to='dashboard.subscraper')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_running', models.BooleanField(default=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_scraper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='dashboard.subscraper')),
            ],
        ),
    ]
