# Generated by Django 5.2.11 on 2026-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscraper',
            name='mongo_db_name',
        ),
        migrations.AddField(
            model_name='mainscraper',
            name='mongo_db_name',
            field=models.CharField(blank=True, help_text='MongoDB database name (leave blank to use global default)', max_length=200),
        ),
        migrations.AddField(
            model_name='mainscraper',
            name='mongo_uri',
            field=models.CharField(blank=True, help_text='MongoDB connection URI for this group (leave blank to use global default)', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscraper',
            name='mongo_collection_name',
            field=models.CharField(blank=True, help_text="Collection name inside the parent scraper group's database", max_length=200),
        ),
    ]
