# Generated by Django 5.2.11 on 2026-02-25 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_main_scraper_mongo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_account_count', models.IntegerField(default=0, help_text='Fixed number of accounts for update scraper (0 = use ratio)')),
                ('new_account_count', models.IntegerField(default=0, help_text='Fixed number of accounts for new scraper (0 = use ratio)')),
                ('update_ratio', models.FloatField(default=0.8, help_text='Ratio of active accounts for update when counts are 0 (auto mode)')),
                ('batch_size_new', models.IntegerField(default=10)),
                ('batch_size_update', models.IntegerField(default=10)),
                ('max_batches_new', models.IntegerField(default=10)),
                ('max_batches_update', models.IntegerField(default=50)),
                ('script_base_path', models.CharField(blank=True, help_text='Base path to scraper scripts directory', max_length=500)),
                ('log_base_path', models.CharField(blank=True, help_text='Base path for log output', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_scraper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_config', to='dashboard.mainscraper')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running_update', 'Running Update'), ('running_new', 'Running New'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dashboard.mainscraper')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('main_scraper', 'email')},
            },
        ),
    ]
